<div class="tab-pane active" id="tab-basic">

    <h4>Basic info</h4>

    <div class="row">
        <div class="form-group">
            <label class="col-sm-4 control-label">Acl Role Name</label>

            <div class="col-sm-4">
                <input type="text" class="form-control" name="name" placeholder="Enter Role Name"
                       value="{{ item.name }}" required autofocus>
            </div>
        </div>

    </div>

</div>
